# action.yml
name: 'Build wasm packages action'
description: 'Build wasm packages using r-wasm/rwasm'
inputs:
  packages:
    description: A string of R package references.
    required: true
  strip:
    description: |
      A set of [directories to remove](https://r-wasm.github.io/rwasm/reference/make_library.html#details) when building the WebAssembly R package library image, or `NULL` to remove nothing (the default). To achieve a smaller bundle size, it is recommended to set `strip` to `"demo, doc, examples, help, html, include, tests, vignette"`.
    default: "NULL"
    required: false
  image-path:
    description: Directory where the R package library filesystem image files should be saved.
    default: "."
    required: false
  repo-path:
    description: Directory where the R package repository should be saved.
    default: "_site"
    required: false
  webr-image:
    description: Docker container image for webR development environment. Switch `main` with a [tagged webR container version](https://github.com/r-wasm/webr/pkgs/container/webr) to use a stable release.
    default: "ghcr.io/r-wasm/webr:main"
    type: string
    required: false
runs:
#  using: 'docker'
#  image: 'Dockerfile'
#  args:
#    - /code.R
#    - ${{ inputs.image-path }}
#    - ${{ inputs.repo-path }}
#    - ${{ inputs.packages }}
#    - ${{ inputs.strip }}
# TODO: Remove this below workaround for https://github.com/orgs/community/discussions/25241
  using: 'composite'
  steps:
    - run: docker build ${{github.action_path}} --build-arg WEBR_IMAGE=${{ inputs.webr-image }} -t r-wasm-build-rwasm:${GITHUB_SHA}
      shell: bash
    - run: |
        docker run --rm -v $(pwd):/github/workspace --workdir /github/workspace r-wasm-build-rwasm:${GITHUB_SHA} \
        /code.R "${{ inputs.image-path }}" "${{ inputs.repo-path }}" "${{ inputs.packages }}" "${{ inputs.strip }}"
      shell: bash
